export type Bail = {
  version: string,
  quarter?:  number,
  irl_previous_year?: number,
  irl_previous?:  number,
  irl_new?:  number,
  income?: number,
  previous_income?: number,
  charges?:  number,
  month?:  number,
  owner_address?:  string,
  owner_name?: string,
  tenant_address?: string,
  tenant_name?:  string,
  garantie?: number,
  address?: string,
  signature?: string,
  amount_works?: number,
  bail_date?: string,
  caution?: boolean,
  invoice_number?: string,
  invoice_date?: string,
  quittance_amount?: string,
  quittance_start_date?: string,
  quittance_end_date?: string,
};
