export type Bail = {
  quarter?:  number,
  irl_previous_year?: number,
  irl_previous?:  number,
  irl_new?:  number,
  previous_income?: number,
  charges?:  number,
  month?:  number,
  owner_address?:  string,
  owner_name?: string,
  tenant_address?: string,
  tenant_name?:  string,
  garantie?: number,
  address?: string,
};
